[package]
name = "drife_m2_ride_sync_pkg"
version = "4.3.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
drife_m2_ride_sync_pkg = "0x0"
